"""
Groundtruth — Pydantic schemas for the FastAPI backend.

Defines the data shapes for every request and response in the system.
AgentTrace carries the agentic metadata (which tool was used, was the
answer revised by the self-critique loop) that the Streamlit UI renders
underneath each answer.
"""

from pydantic import BaseModel, Field


class AgentTrace(BaseModel):
    """Agentic pipeline metadata returned alongside every answer.

    This is what makes Groundtruth visibly agentic in the Streamlit UI —
    the user sees exactly which tool the agent called and whether the
    self-critique loop rewrote the answer.
    """

    tool_used: str = Field(
        description="Name of the tool the agent called: 'get_match_events', "
        "'get_player_stats', 'get_rule_definition', or 'mock' in dev mode."
    )
    was_revised: bool = Field(
        description="True if the self-critique loop rewrote the initial explanation."
    )
    revision_reason: str | None = Field(
        default=None,
        description="One-sentence reason the agent gave for revising its answer. "
        "None if was_revised is False.",
    )


class AskRequest(BaseModel):
    """Payload sent by the Streamlit frontend to POST /ask."""

    question: str = Field(
        min_length=3,
        max_length=500,
        description="The football question asked by the fan in plain English.",
    )
    match_id: str | None = Field(
        default=None,
        description="football-data.org match ID. Optional — rule/tactic questions "
        "do not require a specific match.",
    )


class AskResponse(BaseModel):
    """Structured response returned by POST /ask."""

    answer: str = Field(
        description="Plain-English explanation generated by IBM Granite, "
        "grounded in real match data or rule definitions."
    )
    agent_trace: AgentTrace = Field(
        description="Metadata about the agentic pipeline run: tool used + "
        "whether the self-critique loop revised the answer."
    )


class MatchInfo(BaseModel):
    """Lightweight match summary for the Streamlit dropdown selector."""

    id: str = Field(description="football-data.org numeric match ID as string.")
    home_team: str = Field(description="Home team name.")
    away_team: str = Field(description="Away team name.")
    date: str = Field(description="Match date in ISO 8601 format (YYYY-MM-DD).")
    status: str = Field(
        description="Match status from the API: SCHEDULED, LIVE, IN_PLAY, PAUSED, "
        "FINISHED, POSTPONED, CANCELLED."
    )
